openapi: 3.0.3
info:
  title: Auth Service API
  version: 1.0.0
  description: Authentication endpoints for AI Try-On platform
servers:
  - url: https://api.example.com
paths:
  /auth/send-otp:
    post:
      summary: Send OTP to phone for verification
      operationId: sendOtp
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendOtpRequest'
      responses:
        '200':
          description: OTP dispatched
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendOtpResponse'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '400':
          $ref: '#/components/responses/BadRequest'
  /auth/verify-otp:
    post:
      summary: Verify OTP for phone
      operationId: verifyOtp
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerifyOtpRequest'
      responses:
        '200':
          description: OTP verified
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerifyOtpResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '429':
          $ref: '#/components/responses/TooManyRequests'
  /auth/register:
    post:
      summary: Register a new account
      operationId: register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: User registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          $ref: '#/components/responses/Conflict'
  /auth/login:
    post:
      summary: Login via phone and password
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
  /auth/refresh:
    post:
      summary: Rotate refresh token and issue new tokens
      operationId: refresh
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshRequest'
      responses:
        '200':
          description: Refreshed tokens
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RefreshResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
  /auth/logout:
    post:
      summary: Logout current session
      operationId: logout
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Logout success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
  /auth/logout-all:
    post:
      summary: Logout all sessions for the user
      operationId: logoutAll
      security:
        - bearerAuth: []
      responses:
        '200':
          description: All sessions revoked
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Conflict:
      description: Conflict
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    TooManyRequests:
      description: Rate limit exceeded
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
  schemas:
    SendOtpRequest:
      type: object
      required: [phone]
      properties:
        phone:
          type: string
          description: E.164 formatted phone number
        purpose:
          type: string
          enum: [phone_verify]
        channel:
          type: string
          enum: [sms]
          default: sms
    SendOtpResponse:
      type: object
      properties:
        sent:
          type: boolean
        expiresInSec:
          type: integer
          example: 300
    VerifyOtpRequest:
      type: object
      required: [phone, code]
      properties:
        phone:
          type: string
        code:
          type: string
        purpose:
          type: string
          enum: [phone_verify]
    VerifyOtpResponse:
      type: object
      properties:
        verified:
          type: boolean
    RegisterRequest:
      type: object
      required: [phone, password, role]
      properties:
        phone:
          type: string
        password:
          type: string
          format: password
        role:
          type: string
          enum: [user, vendor]
        autoLogin:
          type: boolean
          default: false
        displayName:
          type: string
        companyName:
          type: string
    RegisterResponse:
      type: object
      properties:
        userId:
          type: string
          format: uuid
        role:
          type: string
        isPhoneVerified:
          type: boolean
        accessToken:
          type: string
        accessTokenExpiresIn:
          type: integer
        refreshToken:
          type: string
        refreshTokenExpiresAt:
          type: string
          format: date-time
    LoginRequest:
      type: object
      required: [phone, password]
      properties:
        phone:
          type: string
        password:
          type: string
          format: password
    LoginResponse:
      type: object
      properties:
        accessToken:
          type: string
        accessTokenExpiresIn:
          type: integer
          example: 900
        refreshToken:
          type: string
        refreshTokenExpiresAt:
          type: string
          format: date-time
        user:
          type: object
          properties:
            id:
              type: string
              format: uuid
            role:
              type: string
            isPhoneVerified:
              type: boolean
    RefreshRequest:
      type: object
      required: [refreshToken]
      properties:
        refreshToken:
          type: string
    RefreshResponse:
      type: object
      properties:
        accessToken:
          type: string
        accessTokenExpiresIn:
          type: integer
          example: 900
        refreshToken:
          type: string
        refreshTokenExpiresAt:
          type: string
          format: date-time
    SuccessResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
    ErrorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
            message:
              type: string
            details:
              type: object


